name: Android CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Simulate Node.js matrix testing
        run: echo "Testing with Node.js version ${{ matrix.node-version }}"

  # Unit Test job (for each environment)
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging1, prod]  # Added matrix for environments
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Run Unit Tests for ${{ matrix.environment }}
        run: ./gradlew test${{ matrix.environment | capitalize }}DebugUnitTest

  # Integration Test job
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Simulated Integration Test
        run: echo "Simulating integration test..."

  # E2E Test job
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Simulated E2E Test
        run: echo "Simulating end-to-end user test..."

  # Build and Upload job (for each environment)
  build-and-upload:
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test, e2e-test]
    strategy:
      matrix:
        environment: [dev, staging1, prod]  # Added matrix for environments
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Build APK for ${{ matrix.environment }}
        run: ./gradlew assemble${{ matrix.environment | capitalize }}Release  # Build APK for each environment
      - name: Upload APK for ${{ matrix.environment }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}-apk
          path: app/build/outputs/apk/${{ matrix.environment }}/release/*.apk

  # Security Scan job
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate SAST
        run: echo "Static analysis done (e.g., SpotBugs simulated)"
      - name: Simulate SCA
        run: echo "Dependency scanning done (simulated)"
      - name: Simulate DAST
        run: echo "Runtime security check simulated"

  # Observability job (optional for logging/metrics)
  observability:
    runs-on: ubuntu-latest
    steps:
      - name: Log Simulation
        run: |
          echo "Logging user activity..."
          echo "User opens dashboard"
      - name: Metric Simulation
        run: |
          echo "Metric: user_login_success=1"
          echo "Metric: workout_complete=1"
      - name: Alerting Simulation
        run: echo "If pipeline fails, send alert (simulated)"
      - name: Synthetic Monitoring
        run: echo "Simulating login → dashboard → logout"
