name: Android CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Simulate Node.js matrix testing
        run: echo "Testing with Node.js version ${{ matrix.node-version }}"

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [Dev, Staging1, Prod]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Add google-services.json for ${{ matrix.flavor }}
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_${{ matrix.flavor }} }}" > app/src/${{ matrix.flavor | toLowerCase }}/google-services.json
        env:
          GOOGLE_SERVICES_JSON_Dev: ${{ secrets.GOOGLE_SERVICES_JSON_Dev }}
          GOOGLE_SERVICES_JSON_Staging1: ${{ secrets.GOOGLE_SERVICES_JSON_Staging1 }}
          GOOGLE_SERVICES_JSON_Prod: ${{ secrets.GOOGLE_SERVICES_JSON_Prod }}
      - name: Run Unit Tests for ${{ matrix.flavor }}
        run: ./gradlew test${{ matrix.flavor }}DebugUnitTest --debug

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Simulated Integration Test
        run: echo "Simulating integration test..."

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Simulated E2E Test
        run: echo "Simulating end-to-end user test..."

  build-and-upload:
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test, e2e-test]
    strategy:
      matrix:
        flavor: [Dev, Staging1, Prod]
        lowercase: [dev, staging1, prod]
        include:
          - flavor: Dev
            lowercase: dev
          - flavor: Staging1
            lowercase: staging1
          - flavor: Prod
            lowercase: prod
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build APK for ${{ matrix.flavor }}
        run: ./gradlew assemble${{ matrix.flavor }}Release
      - name: Upload APK for ${{ matrix.flavor }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.lowercase }}-apk
          path: app/build/outputs/apk/${{ matrix.lowercase }}/release/*.apk

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate SAST
        run: echo "Static analysis done (e.g., SpotBugs simulated)"
      - name: Simulate SCA
        run: echo "Dependency scanning done (simulated)"
      - name: Simulate DAST
        run: echo "Runtime security check simulated"

  observability:
    runs-on: ubuntu-latest
    steps:
      - name: Log Simulation
        run: |
          echo "Logging user activity..."
          echo "User opens dashboard"
      - name: Metric Simulation
        run: |
          echo "Metric: user_login_success=1"
          echo "Metric: workout_complete=1"
      - name: Alerting Simulation
        run: echo "If pipeline fails, send alert (simulated)"
      - name: Synthetic Monitoring
        run: echo "Simulating login → dashboard → logout"
